#Tested on 4.22+


# Subscriptions to OpenConfig paths.
subscriptions:
        - /system/processes
        - /interfaces/interface
        - eos_native:/Kernel/proc
        - eos_native: /Kernel/sysinfo
# Prometheus metrics configuration.
# If you use named capture groups in the path, they will be extracted into labels with the same name.
# All fields are mandatory.
metrics:
        - name: intf
          path: /interfaces/interface
        - name: cputotal
          path: /Kernel/proc/cpu/
          help: CPUtotal
        - name: memorystatus
          path: /Kernel/proc/meminfo/(?P<usageType>(?:memAvailable|memFree|memTotal|buffers|cached))
          help: memory info
        - name: procinfo
          path: /Kernel/proc
        - name: systeminfo
          path: /Kernel/sysinfo
          help: system info
          
