{
 "title": "Prometheus Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "CPU Name",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Host Disk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\", mountpoint=\"/etc/hosts\"}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 20, "w": 16, "x": 6, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (mode) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\", mountpoint=\"/etc/hosts\"} * 100) / node_filesystem_size_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\"}",
     "legendFormat": "Disco disponible"
    }
   ]
  },
  {
   "title": "Pod Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(id) (rate(container_cpu_usage_seconds_total{id=\"/kubepods/besteffort/pod70e18408-a457-422f-8d0b-bcb124a73240/778d8f6332c65a2e0bbfac1bda9134d1938f8fdef798c93d084e8f3f485a1094\"}[1m]))",
     "legendFormat": "Accesspod CPU"
    },
    {
     "expr": "avg by(id) (rate(container_cpu_usage_seconds_total{id=\"/kubepods/besteffort/pod15c42706-2fcd-433c-af92-4032e394f5bd/2f8e4dc183fabd1895c5878b60f3e7c0a41fae0eb11fb845b2fde9546d8a29ba\"}[1m]))",
     "legendFormat": "Router CPU"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=\"/kubepods/besteffort/pod70e18408-a457-422f-8d0b-bcb124a73240/778d8f6332c65a2e0bbfac1bda9134d1938f8fdef798c93d084e8f3f485a1094\"}",
     "legendFormat": "Accesspod Memory Usage"
    },
    {
     "expr": "container_memory_usage_bytes{id=\"/kubepods/besteffort/pod15c42706-2fcd-433c-af92-4032e394f5bd/2f8e4dc183fabd1895c5878b60f3e7c0a41fae0eb11fb845b2fde9546d8a29ba\"}",
     "legendFormat": "Router Memory Usage"
    }
   ]
  },
  {
   "title": "Router Network rates by Flink",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "sort_desc(traffic_rate * 8)", "legendFormat": "{{ interface }}" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"accesspod.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:9100\"}",
     "legendFormat": "Access pod"
    },
    {
     "expr": "up{instance=\"router.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:8080\"}",
     "legendFormat": "Router"
    }
   ]
  },
  {
   "title": "Accesspod Network  rates",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth1\"}[1m]) * 8",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"net1\"}[1m]) * 8",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"vxlanacc\"}[1m]) * 8",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"vxlanint\"}[1m]) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Router Network rates",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(rate(intfCounter{countertype=\"in-octets\"}[1m]) * 8)",
     "legendFormat": "{{ intf }}"
    }
   ]
  }
 ]
}