apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  #prometheus.rules: |-
  #  groups:
  #  - name: devopscube demo alert
  #    rules:
  #    - alert: High Pod Memory
  #      expr: sum(container_memory_usage_bytes) > 1
  #      for: 1m
  #      labels:
  #        severity: slack
  #      annotations:
  #        summary: High Memory Usage
  kernel_rules.yml: |-
    groups:
      - name: test
        rules:
         - record: kernelprocrsswithcommand
           expr: kernelprocrss * on(pid) group_right kernelproc
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - "kernel_rules.yaml"
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

    scrape_configs:
      - job_name: 'knf_access'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "10.1.77.54:9100"
      - job_name: 'knf_cpe'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "10.1.77.57:8080"  
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - 7b2950d8-f92b-4041-9a55-8d1837ad7b0a
