apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: tfm rules
      rules:
      - alert: High traffic rate upstream
        expr: rate(node_network_receive_bytes_total{device="eth1", instance="accesspod.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:9100"}[1m]) *8 > 5500000000
        for: 5s
        labels:
          severity: low
        annotations:
          summary: High Traffic Rate
          description: "There is a high traffic rate in the network with current value: {{ $value }} octects/s)"
      - alert: High traffic rate downstream
        expr: rate(node_network_transmit_bytes_total{device="eth1", instance="accesspod.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:9100"}[1m]) *8 > 9500000000
        for: 5s
        labels:
          severity: low
        annotations:
          summary: High Traffic Rate
          description: "There is a high traffic rate in the network with current value: {{ $value }} octects/s)"
      - alert: Upstream low traffic rate in the network
        expr: rate(intfCounter{countertype="in-octets", intf="Ethernet1"}[1m]) * 8 < 1000000
        for: 10m
        labels:
          severity: low
        annotations:
          summary: Low Traffic Rate
          description: "There is low traffic rate in the network with current value: {{ $value }} octects/s)"
      - alert: Downstream low traffic rate in the network
        expr: rate(intfCounter{countertype="out-octets", intf="Ethernet2"}[1m]) * 8 < 1000000
        for: 10m
        labels: 
          severity: low
        annotations:
          summary: Low Traffic Rate
          description: "There is low traffic rate in the network with current value: {{ $value }} octects/s)"
      - alert: Router CPU is near the limit
        expr: sum by(id) (rate(container_cpu_usage_seconds_total{id="/kubepods/besteffort/pod15c42706-2fcd-433c-af92-4032e394f5bd/2f8e4dc183fabd1895c5878b60f3e7c0a41fae0eb11fb845b2fde9546d8a29ba"}[1m])) > 0.9
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: High CPU use in router
          description: "There is a high CPU use in router with current value: {{ $value }}"
      - alert: Router memory 
        expr: container_memory_usage_bytes{id="/kubepods/besteffort/pod15c42706-2fcd-433c-af92-4032e394f5bd/2f8e4dc183fabd1895c5878b60f3e7c0a41fae0eb11fb845b2fde9546d8a29ba"} > 2000000000
        for: 10s
        labels:
          severity: critical 
        annotations:
          summary: High memory use in router
          description: "Router memory is using too much resources: {{ $value }}"
      - alert: Router not detected 
        expr: up{instance="router.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:8080"} < 1
        for: 10s
        labels:
          severity: critical 
        annotations:
          summary: Router not detected
          description: "There are some problems with the Router"
      - alert: Access pod not detected
        expr: up{instance="accesspod.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:9100"} < 1         
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Access pod not detected      
          description: "There are some problems with the Access pod"
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
        - "prometheus.rules"
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"

    scrape_configs:
      - job_name: 'knf_access'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "accesspod.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:9100"
      - job_name: 'knf_cpe'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "router.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:8080"
      - job_name: 'cadvisor'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "cadvisor:8080"
      - job_name: 'pushgw'
        honor_labels: true
        scrape_interval: 5s
        static_configs:
          - targets:
             - "pushgateway:9091"
  
#      - job_name: 'knf'
#        kubernetes_sd_configs:
#        - role: service
#          namespaces:
#            names:
#              - 19d72910-a9a6-4786-8e91-77cb8dd15ffa
#              - monitoring
