apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  #prometheus.rules: |-
  #  groups:
  #  - name: devopscube demo alert
  #    rules:
  #    - alert: High Pod Memory
  #      expr: sum(container_memory_usage_bytes) > 1
  #      for: 1m
  #      labels:
  #        severity: slack
  #      annotations:
  #        summary: High Memory Usage
  kernel_rules.yml: |-
    groups:
     - name: test
       rules:
        - record: kernelprocrsswithcommand
          expr: kernelprocrss * on(pid) group_right kernelproc

  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
        - "kernel_rules.yml"
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

    scrape_configs:
      - job_name: 'knf_access'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "helmchartrepo-accesschart-0045899191.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:9100"
      - job_name: 'knf_cpe'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "helmchartrepo-router-0068913436.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:8080"
      - job_name: 'cadvisor'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "cadvisor:8080"  
#      - job_name: 'knf'
#        kubernetes_sd_configs:
#        - role: service
#          namespaces:
#            names:
#              - 19d72910-a9a6-4786-8e91-77cb8dd15ffa
#              - monitoring
