apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: traffic rate unexpected
      rules:
      - alert: High traffic rate
        expr: traffic_rate{interface="Ethernet1"} > 300
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: High Traffic Rate
          description: "{{$labels.instance }} has a high traffic rate (current value: {{ $value }} octects/s)"
  kernel_rules.yml: |-
    groups:
     - name: test
       rules:
        - record: kernelprocrsswithcommand
          expr: kernelprocrss * on(pid) group_right kernelproc

  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
        - "kernel_rules.yml"
        - "prometheus.rules"
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"

    scrape_configs:
      - job_name: 'knf_access'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "accesspod.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:9100"
      - job_name: 'knf_cpe'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "router.19d72910-a9a6-4786-8e91-77cb8dd15ffa.svc:8080"
      - job_name: 'cadvisor'
        scrape_interval: 5s
        static_configs:
          - targets:
              - "cadvisor:8080"
      - job_name: 'pushgw'
        honor_labels: true
        scrape_interval: 5s
        static_configs:
          - targets:
             - "pushgateway:9091"
  
#      - job_name: 'knf'
#        kubernetes_sd_configs:
#        - role: service
#          namespaces:
#            names:
#              - 19d72910-a9a6-4786-8e91-77cb8dd15ffa
#              - monitoring
