apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 9091
    targetPort: 9091
    nodePort: 30171
  selector:
    app: pushgateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pushgateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      namespace: monitoring
      labels:
        app: pushgateway
    spec:
      containers:
        - image: prom/pushgateway:latest
          name: pushgw
          ports:
            - containerPort: 9091
              protocol: TCP
