apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: podnet2
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/podnet2
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "ovs",
      "bridge": "PodNet2",
      "ipam": {
        "type": "static"
      }
    }'
