apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: monitoring
  labels:
    app: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka-server
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LOG_DIRS 
          value: "/tmp/kafka-logs"
        - name: KAFKA_CREATE_TOPICS
          value: "gnmic-telemetry-1:1:1,gnmic-telemetry-2:1:1,gnmic-telemetry-3:1:1,gnmic-telemetry-4:1:1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-server
  template:
    metadata:
      labels:
        app: zookeeper-server
    spec:
      containers:
      - name: zoo
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
