apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: monitoring
  labels:
    name: kafka-server
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    targetPort: 9092
    nodePort: 30002
    protocol: TCP
  selector:
    app: kafka-server
---

apiVersion: v1
kind: Service
metadata:
  name: zoo
  labels:
    app: zookeeper-server
spec:
  ports:
  - name: zookeeper-port
    port: 2181
    protocol: TCP
  selector:
    app: zookeeper-server
